### ISSUE TITLE
Javadoc build failure

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.ui#484] opened 2023-03-20 14:59 UTC
In latest I-build javadoc build fails with the issues shown at https://download.eclipse.org/eclipse/downloads/drops4/I20230320-0330/compilelogs/jdt.doc.isv.javadoc.txt

**Comment by iloveeclipse** [comment] 2023-03-21 09:16
Last successful execution is https://download.eclipse.org/eclipse/downloads/drops4/I20230316-1800/
After that we've switched a lot of bundles to Java 17, platform tests were not running / recorded, and the first fail is in https://download.eclipse.org/eclipse/downloads/drops4/I20230320-0330/testResults.php

So we have regression between I20230316-1800 and I20230320-0330.

I don't see any breaking changes in JDT UI code here, so it must be something related to recent platform / releng activities.

**Comment by iloveeclipse** [comment] 2023-03-21 10:46
See "similar" issue https://github.com/eclipse-platform/eclipse.platform.common/issues/18 and fix https://github.com/eclipse-platform/eclipse.platform.common/pull/19/files.
However, why should only JDT UI build fail?

**Comment by sravanlakkimsetti** [comment] 2023-03-21 13:12
@iloveeclipse I can see 1 possible cause. org.eclipse.core.runtime is used in jdt.ui. I see that o.e.core.runtime updated to java 17 but the jdt.ui plugins that use o.e.core.runtime are set at java-11. I think we need to update jdt.ui bundles to java-17.

**Comment by iloveeclipse** [comment] 2023-03-21 13:27
@sravanlakkimsetti : thanks, that is surely not only one place where JDT (which is still on Java 11) uses platform that is on Java 17. But this implies that **somewhere** we run **some** task on Java 11 runtime that is unable to read Java 17 class files - **where** would be this output? Is this "cut out" from [jdt.doc.isv.javadoc.txt](https://download.eclipse.org/eclipse/downloads/drops4/I20230320-0330/compilelogs/jdt.doc.isv.javadoc.txt) ? 

I would **love** to see this build chain explained in the wiki. Who starts which process in which script and how that generates at the end the xyz.javadoc.txt files.

**Comment by sravanlakkimsetti** [comment] 2023-03-21 14:24
I jotted down some points on how build is triggered in the wiki page. 
May be adding more doclint or javadoc debug options might give us more information. we can add more options in jdtOptions.txt file

**Comment by iloveeclipse** [comment] 2023-03-21 14:35
@sravanlakkimsetti : thanks. Where, in which log are we supposed to see this output:
```
org.eclipse.jdt.doc.isv/buildDoc.xml - generateJavadoc:
      Using javadocExecutable:
```
from https://github.com/eclipse-platform/eclipse.platform.common/blob/54455a117960237d69a9d840e61872641cafdaaa/bundles/org.eclipse.jdt.doc.isv/buildDoc.xml#LL106C7-L107C31

**Comment by sravanlakkimsetti** [comment] 2023-03-21 14:50
this is the [exact line](https://github.com/eclipse-platform/eclipse.platform.common/blob/54455a117960237d69a9d840e61872641cafdaaa/bundles/org.eclipse.jdt.doc.isv/buildDoc.xml#L141-L143) where we execute javadoc and generate the log doc.bin.log. 

The doc.bin.log is renamed [here](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/1bbda0a96dc04e93bdc1bb91813a5d98b5659653/eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml#L49-L78)

the rename happens during `gather eclipse parts` stage.

**Comment by iloveeclipse** [comment] 2023-03-21 14:53
@sravanlakkimsetti : yes, I see it, but in which **log** file in the SDK build do we see the output from the **echo** task that runs [40 lines above](https://github.com/eclipse-platform/eclipse.platform.common/blob/54455a117960237d69a9d840e61872641cafdaaa/bundles/org.eclipse.jdt.doc.isv/buildDoc.xml#L106)

**Comment by iloveeclipse** [comment] 2023-03-21 15:10
Arrgh, OK, I will check that. Any idea why `-quiet` was used at all? Too much output?

**Comment by akurtakov** [comment] 2023-03-21 15:17
FWIW, the process is too cumbersome and if there is agreement to move javadoc to separate bundles that contain only the javadoc I'm sure that we can craft something far easier to manage. Ideally, having one such bundle per git repo so javadoc errors are flagged even by verification builds. @laeubi already asked and tried things in that area for equinox and platform.

**Comment by laeubi** [comment] 2023-03-21 15:24
Actually tycho has a "document bundle" plugin, that *seems* to work towards the direction of having an "eclipse-javadoc-tool", but it is / was not really used, so if there are some demands I'm open to revive / modernize the plugin but I'm not very familiar with the current "doc-builds" and what are the expected outcomes are.

**Comment by laeubi** [comment] 2023-03-21 15:34
Tycho always require Java 17 to *run* so this usually should already use Java 17, *but* the eclipse run itself calls **ant** so I'm not sure if/how there might be a different setting for that, there is a file in that folder that seems to configure some jdt options (guessing by name):
https://github.com/eclipse-platform/eclipse.platform.common/blob/54455a117960237d69a9d840e61872641cafdaaa/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt

**Comment by laeubi** [comment] 2023-03-21 15:45
By the way as far as I know this does not only generates javadoc but also the extension point docs and alike...

**Comment by iloveeclipse** [comment] 2023-03-22 08:24
@sravanlakkimsetti : I don't see anything in any log file that would indicate the "echo" from https://github.com/eclipse-platform/eclipse.platform.common/pull/128/files is there.

I'm looking for example for string `org.eclipse.jdt.doc.isv/buildDoc.xml` or `generateJavadoc` in 
- https://download.eclipse.org/eclipse/downloads/drops4/I20230321-1800/logs.php#console
- and there in https://download.eclipse.org/eclipse/downloads/drops4/I20230321-1800/testresults/consolelogs/ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17_consolelog.txt

So I assume the pom change has no effect => the javadoc build is triggered from somewhere else?

**Comment by sravanlakkimsetti** [comment] 2023-03-22 08:45
I see the echo statements in [mb220_buildSdkPatch.sh.log](https://download.eclipse.org/eclipse/downloads/drops4/I20230321-1800/buildlogs/mb220_buildSdkPatch.sh.log). Please refer to line numbers 30550 and 30551. 

build for org.eclipse.jdt.doc.isv starts at 28960 and ends at 31073. 
Ant build log is from 29107 to 31045

**Comment by iloveeclipse** [comment] 2023-03-24 05:34
Looks like moving JDT UI  bundles to Java 17 via https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/493 fixed **gazillions** of errors related to jdt.ui. 

Remaining one will be probably fixed either via https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/210 or by ant / debug bundles updates, I will try to do this today. 

```
../../../eclipse.platform/ant/org.eclipse.ant.launching/src/org/eclipse/ant/launching/IAntLaunchConstants.java:17: error: package org.eclipse.core.externaltools.internal does not exist
import org.eclipse.core.externaltools.internal.IExternalToolConstants;
                                              ^
1 error
```

**Comment by akurtakov** [comment] 2023-03-29 07:07
I have touched doc bundles via https://ci.eclipse.org/releng/job/Touch_doc_bundles/62/ and will trigger I-build now so we can see the exact state of the issue.

**Comment by iloveeclipse** [comment] 2023-03-29 07:20
> I have touched doc bundles via

I've added this to the wiki: https://github.com/eclipse-platform/.github/wiki/Javadoc-validation

Can you please add explanation why, in which cases is this needed?

**Comment by sravanlakkimsetti** [comment] 2023-03-29 08:10
> > I have touched doc bundles via
> 
> I've added this to the wiki: https://github.com/eclipse-platform/.github/wiki/Javadoc-validation
> 
> Can you please add explanation why, in which cases is this needed?

Adding the explanation now. A bit lengthy will take some time.

**Comment by sravanlakkimsetti** [comment] 2023-03-29 08:48
Added https://github.com/eclipse-platform/.github/wiki/Javadoc-validation#touch_doc_bundles. Please check where this is sufficient?

**Comment by iloveeclipse** [comment] 2023-03-29 09:00
> I have touched doc bundles via https://ci.eclipse.org/releng/job/Touch_doc_bundles/62/ and will trigger I-build now so we can see the exact state of the issue.

Still same error as before:
https://download.eclipse.org/eclipse/downloads/drops4/I20230329-0310/compilelogs/jdt.doc.isv.javadoc.txt

```
../../../eclipse.platform/ant/org.eclipse.ant.launching/src/org/eclipse/ant/launching/IAntLaunchConstants.java:17: error: package org.eclipse.core.externaltools.internal does not exist
import org.eclipse.core.externaltools.internal.IExternalToolConstants;
                                              ^
1 error
```

**Comment by iloveeclipse** [comment] 2023-03-30 06:12
> To proof that we need [eclipse-platform/eclipse.platform#356](https://github.com/eclipse-platform/eclipse.platform/pull/356) fixes to be merged.

Did not help, but may be we miss touch on doc bundles now, so I've triggered 
https://ci.eclipse.org/releng/job/Touch_doc_bundles/63/

Will start IBiild once we also have this fix for  JDT crashes: https://github.com/eclipse-pde/eclipse.pde/pull/542

**Comment by iloveeclipse** [comment] 2023-03-30 07:18
> Triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28/36/

Failed, see https://github.com/eclipse-platform/eclipse.platform.releng/issues/222.

Triggered a new one: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28/37/

**Comment by iloveeclipse** [comment] 2023-03-30 09:06
Still same error in https://download.eclipse.org/eclipse/downloads/drops4/I20230330-0310/logs.php#javadoc :
https://download.eclipse.org/eclipse/downloads/drops4/I20230330-0310/compilelogs/jdt.doc.isv.javadoc.txt
```
../../../eclipse.platform/ant/org.eclipse.ant.launching/src/org/eclipse/ant/launching/IAntLaunchConstants.java:17: error: package org.eclipse.core.externaltools.internal does not exist
import org.eclipse.core.externaltools.internal.IExternalToolConstants;
                                              ^
1 error
```

**Comment by iloveeclipse** [comment] 2023-04-05 15:38
I have no time to investigate it further, especially there is no explanation how one can run the build only for the doc bundles without the rest of SDK.

=> workaround to build only subset of API reference for M1:

https://github.com/eclipse-platform/eclipse.platform.common/pull/133

**Comment by iloveeclipse** [comment] 2023-04-06 05:17
> I have no time to investigate it further, especially there is no explanation how one can run the build only for the doc bundles without the rest of SDK.
> 
> => workaround to build only subset of API reference for M1 (that at least produces non-empty doc bundles and I see no errors anymore opening help in built SDK):
> 
> [eclipse-platform/eclipse.platform.common#133](https://github.com/eclipse-platform/eclipse.platform.common/pull/133)

Interestingly, even if my local SDK build succeeded, [SDK build](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/) still has same problem.

So something is missing, even if the doc bundles were touched: https://github.com/eclipse-platform/eclipse.platform.common/commit/df307d9bbf5edf0ed0eee4134cc68c3bb6652e22

**Comment by iloveeclipse** [comment] 2023-04-06 06:15
> Interestingly, even if my local SDK build succeeded, [SDK build](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/) still has same problem.

I was wrong. My local build is still broken in same way like "official" one, but it is now **less** broken as the state I saw before with gazillions of JDT UI errors, so I've assumed it is OK, which is not.

**Comment by iloveeclipse** [comment] 2023-04-06 15:17
This is the arguments file that the javadoc command executes:
```
-quiet
-encoding "UTF-8"
-charset "UTF-8"
-sourcepath "../../../eclipse.jdt.core/org.eclipse.jdt.annotation/src:../../../eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/src:../../../eclipse.jdt.core/org.eclipse.jdt.apt.core/src:../../../eclipse.jdt.core/org.eclipse.jdt.core/antadapter:../../../eclipse.jdt.core/org.eclipse.jdt.core/codeassist:../../../eclipse.jdt.core/org.eclipse.jdt.core/compiler:../../../eclipse.jdt.core/org.eclipse.jdt.core/dom:../../../eclipse.jdt.core/org.eclipse.jdt.core/eval:../../../eclipse.jdt.core/org.eclipse.jdt.core/formatter:../../../eclipse.jdt.core/org.eclipse.jdt.core/model:../../../eclipse.jdt.core/org.eclipse.jdt.core/search:../../../eclipse.jdt.debug/org.eclipse.jdt.debug/eval:../../../eclipse.jdt.debug/org.eclipse.jdt.debug/jdi:../../../eclipse.jdt.debug/org.eclipse.jdt.debug/model:../../../eclipse.jdt.debug/org.eclipse.jdt.debug.ui/ui:../../../eclipse.jdt.debug/org.eclipse.jdt.launching/launching:../../../eclipse.jdt.ui/org.eclipse.jdt.core.manipulation/common:../../../eclipse.jdt.ui/org.eclipse.jdt.core.manipulation/refactoring:../../../eclipse.jdt.ui/org.eclipse.jdt.junit/src:../../../eclipse.jdt.ui/org.eclipse.jdt.junit.core/src:../../../eclipse.jdt.ui/org.eclipse.jdt.junit.runtime/src:../../../eclipse.jdt.ui/org.eclipse.jdt.junit4.runtime/src:../../../eclipse.jdt.ui/org.eclipse.jdt.junit5.runtime/src:../../../eclipse.jdt.ui/org.eclipse.jdt.ui/core extension:../../../eclipse.jdt.ui/org.eclipse.jdt.ui/core refactoring:../../../eclipse.jdt.ui/org.eclipse.jdt.ui/internal compatibility:../../../eclipse.jdt.ui/org.eclipse.jdt.ui/ui:../../../eclipse.jdt.ui/org.eclipse.jdt.ui/ui refactoring:../../../eclipse.platform/ant/org.eclipse.ant.launching/src:../../../eclipse.platform/ant/org.eclipse.ant.ui/Ant Editor:../../../eclipse.platform/ant/org.eclipse.ant.ui/Ant Tools Support"
-d reference/api
-classpath ${bootclasspath}:target/dependency/org.apache.ant-1.10.12.v20211102-1452-lib/ant.jar.jar:target/dependency/org.junit-4.13.2.v20211018-1956.jar:target/dependency/icu4j-72.1.jar:target/dependency/org.osgi.service.prefs-1.1.2.jar:target/dependency/org.osgi.service.event-1.4.1.jar:target/dependency/org.osgi.service.cm-1.6.1.jar:../../../rt.equinox.framework/bundles/org.eclipse.osgi/supplement/target/classes:../../../eclipse.jdt.core/org.eclipse.jdt.apt.core/mirrorapi.jar:../../../eclipse.jdt.debug/org.eclipse.jdt.debug/jdi.jar:../../../eclipse.jdt.ui/org.eclipse.jdt.core.manipulation/target/classes:../../../eclipse.jdt.ui/org.eclipse.jdt.junit/target/classes:../../../eclipse.jdt.ui/org.eclipse.jdt.junit.core/target/classes:../../../eclipse.jdt.ui/org.eclipse.ltk.core.refactoring/target/classes:../../../eclipse.jdt.ui/org.eclipse.ltk.ui.refactoring/target/classes:../../../eclipse.platform/ant/org.eclipse.ant.core/target/classes:../../../eclipse.platform.debug/org.eclipse.core.externaltools/target/classes:../../../eclipse.platform.debug/org.eclipse.core.variables/target/classes:../../../eclipse.platform.debug/org.eclipse.debug.core/target/classes:../../../eclipse.platform.debug/org.eclipse.debug.ui/target/classes:../../../eclipse.platform.debug/org.eclipse.ui.console/target/classes:../../../eclipse.platform.debug/org.eclipse.ui.externaltools/target/classes:../../../eclipse.platform/resources/bundles/org.eclipse.core.filesystem/target/classes:../../../eclipse.platform/resources/bundles/org.eclipse.core.resources/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.contenttype/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.expressions/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.jobs/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.runtime/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.runtime.content/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.runtime.jobs/target/classes:../../../eclipse.platform/runtime/bundles/org.eclipse.core.runtime.preferences/target/classes:../../../eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/target/classes:../../../eclipse.platform/team/bundles/org.eclipse.compare/target/classes:../../../eclipse.platform/team/bundles/org.eclipse.compare.core/target/classes:../../../eclipse.platform/team/bundles/org.eclipse.team.core/target/classes:../../../eclipse.platform/team/bundles/org.eclipse.team.ui/target/classes:../../../eclipse.platform.text/org.eclipse.core.filebuffers/target/classes:../../../eclipse.platform.text/org.eclipse.jface.text/target/classes:../../../eclipse.platform.text/org.eclipse.search/target/classes:../../../eclipse.platform.text/org.eclipse.text/target/classes:../../../eclipse.platform.text/org.eclipse.ui.editors/target/classes:../../../eclipse.platform.text/org.eclipse.ui.workbench.texteditor/target/classes:../../../eclipse.platform.ua/org.eclipse.help/target/classes:../../../eclipse.platform.ua/org.eclipse.help.ui/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.core.commands/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.jface/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui.forms/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.e4.ui.ide/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui.ide/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui.navigator/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui.views/target/classes:../../../eclipse.platform.ui/bundles/org.eclipse.ui.workbench/target/classes:../../../equinox/bundles/org.eclipse.equinox.app/target/classes:../../../equinox/bundles/org.eclipse.equinox.common/target/classes:../../../equinox/bundles/org.eclipse.equinox.bidi/target/classes:../../../equinox/bundles/org.eclipse.equinox.preferences/target/classes:../../../equinox/bundles/org.eclipse.equinox.registry/target/classes:../../../equinox/bundles/org.eclipse.osgi/target/classes:../../../equinox/bundles/org.eclipse.osgi.services/target/classes:../../../equinox/bundles/org.eclipse.osgi.util/target/classes:../../../rt.equinox.p2/bundles/org.eclipse.equinox.frameworkadmin/target/classes
-breakiterator
-use
-splitIndex
-windowtitle "Eclipse JDT API Specification"
-doctitle "Eclipse JDT API Specification"
-header "<span style='font-size:small'><b>Eclipse JDT</b><br>2023-06 (4.28)</span>"
-bottom "<br><span style='font-size:small;float:right'>Copyright (c) 2000, 2023 Eclipse Contributors and others. All rights reserved.</span><span style='font-size:small'><a href='{@docRoot}/../misc/api-usage-rules.html'>Guidelines for using Eclipse APIs.</a></span>"
-group "Java development tools core packages" "org.eclipse.jdt.core:org.eclipse.jdt.core.*"
-group "Java development tools UI packages" "org.eclipse.jdt.ui:org.eclipse.jdt.ui.*"
-group "Java development tools APT packages" "org.eclipse.jdt.apt.core:org.eclipse.jdt.apt.core.*:com.sun.mirror.*"
-group "Java development tools debug and launching packages" "org.eclipse.ant.launching:org.eclipse.ant.ui.launching:org.eclipse.jdt.debug.*:org.eclipse.jdt.launching:org.eclipse.jdt.launching.*"
-group "Java development tools JUnit packages" "org.eclipse.jdt.junit:org.eclipse.jdt.junit.*"
-link https://docs.oracle.com/en/java/javase/17/docs/api
-link https://docs.osgi.org/javadoc/osgi.core/8.0.0/
-link https://docs.osgi.org/javadoc/osgi.enterprise/7.0.0/
-linkoffline ./../../../org.eclipse.platform.doc.isv/reference/api ../org.eclipse.platform.doc.isv/reference/api
-tag 'noimplement:a:Restriction:'
-tag 'noextend:a:Restriction:'
-tag 'noreference:a:Restriction:'
-tag 'noinstantiate:a:Restriction:'
-tag 'nooverride:a:Restriction:'
-tag 'category:a:Category:'
-Xdoclint:reference,html
-Xmaxwarns 10000
-Xmaxerrs 10000
-notimestamp

org.eclipse.jdt.annotation

org.eclipse.jdt.core
org.eclipse.jdt.core.compiler
org.eclipse.jdt.core.compiler.batch
org.eclipse.jdt.core.dom
org.eclipse.jdt.core.dom.rewrite
org.eclipse.jdt.core.eval
org.eclipse.jdt.core.formatter
org.eclipse.jdt.core.index
org.eclipse.jdt.core.jdom
org.eclipse.jdt.core.manipulation
org.eclipse.jdt.core.refactoring
org.eclipse.jdt.core.refactoring.descriptors
org.eclipse.jdt.core.refactoring.participants
org.eclipse.jdt.core.search
org.eclipse.jdt.core.util

org.eclipse.jdt.ui
org.eclipse.jdt.ui.actions
org.eclipse.jdt.ui.cleanup
org.eclipse.jdt.ui.dialogs
org.eclipse.jdt.ui.jarpackager
org.eclipse.jdt.ui.refactoring
org.eclipse.jdt.ui.search
org.eclipse.jdt.ui.text
org.eclipse.jdt.ui.text.folding
org.eclipse.jdt.ui.text.java
org.eclipse.jdt.ui.text.java.correction
org.eclipse.jdt.ui.text.java.hover
org.eclipse.jdt.ui.wizards

com.sun.mirror.apt
com.sun.mirror.declaration
com.sun.mirror.type
com.sun.mirror.util
org.eclipse.jdt.apt.core.build
org.eclipse.jdt.apt.core.env
org.eclipse.jdt.apt.core.util

org.eclipse.ant.launching
org.eclipse.ant.ui.launching
org.eclipse.jdt.debug.core
org.eclipse.jdt.debug.eval
org.eclipse.jdt.debug.ui
org.eclipse.jdt.debug.ui.actions
org.eclipse.jdt.debug.ui.breakpoints
org.eclipse.jdt.debug.ui.launchConfigurations
org.eclipse.jdt.launching
org.eclipse.jdt.launching.environments
org.eclipse.jdt.launching.sourcelookup
org.eclipse.jdt.launching.sourcelookup.advanced
org.eclipse.jdt.launching.sourcelookup.containers

org.eclipse.jdt.junit
org.eclipse.jdt.junit.launcher
org.eclipse.jdt.junit.model
org.eclipse.jdt.junit.wizards
```

And with exact that list in my local SDK build directory tree I don't see any errors.

BUT!

If I change `:../../../eclipse.platform.debug/org.eclipse.core.externaltools/target/classes:`  to  `:../../../eclipse.platform.debug/org.eclipse.core.externaltools/target/classesXXX:`

I see exact the error we see on the "official" build: 

```
cd eclipse.platform.releng.aggregator/eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv

/usr/lib/jvm/jdk-17_adoptium/bin/javadoc @/data/git/eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/argsfile1.txt -J-Xmx1000M
../../../eclipse.platform/ant/org.eclipse.ant.launching/src/org/eclipse/ant/launching/IAntLaunchConstants.java:17: error: package org.eclipse.core.externaltools.internal does not exist
import org.eclipse.core.externaltools.internal.IExternalToolConstants;
                                              ^
1 error
```

What is really strange, because the externaltools/target/classes directory IS there **after** SDK build and the classpath I've extracted from ant log file works **after** the build but not **during** the build.

*And in fact, it looks like the externaltools are compiled **after** we build javadocs!!!*

I see this output AFTER the build fails!
```
[INFO] --------< org.eclipse.platform:org.eclipse.core.externaltools >---------
[INFO] Building [bundle] External Tools Headless Support 1.3.0-SNAPSHOT [159/520]
[INFO] ---------------------------[ eclipse-plugin ]---------------------------
[INFO] Resolving dependencies of MavenProject: org.eclipse.platform:org.eclipse.core.externaltools:1.3.0-SNAPSHOT @
```

**Comment by iloveeclipse** [comment] 2023-04-06 15:24
And here is the order that maven prints at beginning:
```
[INFO] Reactor Build Order:
...
[INFO] org.eclipse.platform.doc.isv                            [eclipse-plugin]
[INFO] org.eclipse.jdt.doc.isv                                 [eclipse-plugin]
[INFO] org.eclipse.jdt.debug.ui                                [eclipse-plugin]
[INFO] org.eclipse.jdt.apt.pluggable.core                      [eclipse-plugin]
[INFO] org.eclipse.jdt.doc.user                                [eclipse-plugin]
[INFO] [bundle] External Tools Headless Support                [eclipse-plugin]
```

Note: javadoc requires **built*** code of external tools bundle that is compiled **after** javadoc bundles.

**Comment by laeubi** [comment] 2023-04-06 15:27
If `org.eclipse.jdt.doc.isv` requires `org.eclipse.core.externaltools` to be build before it should at best mention this as an additional dependency.

**Comment by iloveeclipse** [comment] 2023-04-06 15:31
So was there a tycho / maven change that changed the order of dependencies?
I don't see **any** of many dependencies the javadoc requires defined in eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF

**Comment by laeubi** [comment] 2023-04-06 15:41
You see additional dependencies are defined here:
https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.jdt.doc.isv/pom.xml

if there is no dependency, this means the project can be build any time before/after or even in parallel. Also if I understand one needs to "touch" files to have things changed, so maybe this problem exits longer but was not noticed, or some dependency changed and the order changed therefore slightly...

**Comment by iloveeclipse** [comment] 2023-04-06 15:47
I've set https://github.com/eclipse-platform/eclipse.platform.common/pull/136 that adds this dependency.

But thinking more, **all** of the bundles we refer via target/classes, starting with [this line](https://github.com/eclipse-platform/eclipse.platform.common/blob/d44d20bc3e1e802f8a16555d09fe9d9153b03597/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt#L46) should be on the pom file dependencies list?

**Comment by iloveeclipse** [comment] 2023-04-07 09:54
Fixed with https://download.eclipse.org/eclipse/downloads/drops4/I20230407-0200/testResults.php

**Closed by iloveeclipse** 2023-04-07 09:54 UTC

**Comment by iloveeclipse** [comment] 2023-04-11 08:11
Note: I've added more dependencies to maven via https://github.com/eclipse-platform/eclipse.platform.common/pull/139
