### ISSUE TITLE
Mouse hover cannot prompt for import,but ,ctrl+shift+o is ok.

### ISSUE THREAD

**Issue by 1083** [eclipse-jdt/eclipse.jdt.ui#504] opened 2023-03-30 01:49 UTC
Mouse hover cannot prompt for import,but ,ctrl+shift+o is ok.
ECLIPSE VER:2023-03
for example: 	ObjectMapper objectMapper = new ObjectMapper();
![ec](https://user-images.githubusercontent.com/65584187/228709212-aacea669-412a-489f-b568-a0cfd5ed1d26.JPG)
![bug1](https://user-images.githubusercontent.com/65584187/228709815-c59fd966-80e6-45f6-a58c-19fa4f447e55.JPG)
![but2](https://user-images.githubusercontent.com/65584187/228709824-2e28cc0e-d411-449d-8b66-9b0ce9f2a1b7.JPG)

**Comment by jjohnstn** [comment] 2023-03-31 18:01
This is a duplicate of: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/485 which was a regression in 2023-03.  The problem has been fixed and will be part of the 4.28 M1 milestone which will be released soon.  It is already in current I-builds.

**Closed by jjohnstn** 2023-03-31 18:01 UTC
