### ISSUE TITLE
Bug：Move method depends on the static method of the original class and the static method of the inner class

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1305] opened 2024-04-02 03:32 UTC
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/fca21e77-80ba-44d3-9f3e-e481400d912c)

Refactoring results:

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/08719b62-6406-42c2-9073-c8430a1e4e57)

**Comment by jukzi** [comment] 2024-04-16 12:15
Duplicate of #1306

**Closed by jukzi** 2024-04-16 12:15 UTC
