### ISSUE TITLE
Bug:  Move methods rely on static inner classes

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1306] opened 2024-04-02 03:39 UTC
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/aa6f2057-d751-4602-85bc-3f22c47369af)

Refactoring result:

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/94ef40fa-d28a-4e6e-b51b-5316a2efd044)

**Comment by jukzi** [comment] 2024-04-16 12:14
@DongChunHao the bug description gives very few details. Please fully describe which actions are necessary to reproduce, what you expect and which version you used.

**Comment by jjohnstn** [comment] 2024-05-29 16:57
This is fixed by #1412

**Comment by jjohnstn** [comment] 2024-06-07 15:25
Closing since #1412 is merged.

**Closed by jjohnstn** 2024-06-07 15:25 UTC
Labels: bug
