### ISSUE TITLE
Bugzilla 570171 - Code cleanup "merge conditions of if / else" does not handle instanceof pattern matching 

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.ui#1215] opened 2024-02-19 01:41 UTC
Source > Cleanup ... with "merge conditions of if / else" does not handle instanceof pattern correctly. 

Example code:

    Exception e = new IOException();
    if (e instanceof IOException io)
        throw io;
    else if (e.getCause() instanceof IOException io)
        throw io;

After cleanup the code does not compile:

    if ((e instanceof IOException io) || (e.getCause() instanceof IOException io))
        throw io;

**Comment by jjohnstn** [comment] 2024-02-21 22:44
Closed as duplicate of #1200 which has patch waiting for 4.32 M1 to open

**Closed by jjohnstn** 2024-02-21 22:44 UTC
Labels: bug
