### ISSUE TITLE
Bug: Move method refactoring relies on instantiation and invocation of static internal interfaces

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1302] opened 2024-04-02 03:02 UTC
Move **_myMethod()_** to **_TargetClass_**

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/b196b0ef-bcc1-4f4b-a466-30ec5d07fd68)

Refactoring results：

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/166308ac-f1ba-470b-9326-2310e0c905d0)

**Comment by jjohnstn** [comment] 2024-05-17 19:33
Closing as duplicate of #1301 (test works with #1412 applied)

**Closed by jjohnstn** 2024-05-17 19:33 UTC
Labels: bug
