### ISSUE TITLE
Extracting a superclass from an inner static class extracts the outer class instead

### ISSUE THREAD

**Issue by khatchad** [eclipse-jdt/eclipse.jdt.ui#152] opened 2022-07-11 16:23 UTC
## Steps
1. Select an inner static class in the UI.
2. Select the "extract superclass" refactoring option.

## Expect Result
A superclass is extracted from the selected, inner static class.

## Actual Result
A superclass is extracted from the outer class.

## Example Problematic Input
```java
class A {
  static class B {
// ...
}
```
Extracting a superclass from `B` attempts to exact a superclass from `A`.

**Comment by khatchad** [comment] 2022-07-11 16:23
Related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=304473.

**Comment by tsmaeder** [comment] 2022-07-25 08:40
If you select a member of the class `B` in the above example, the refactoring correctly extracts a superclass of `B`. As far as I can tell from the code in `ExtractSupertypeProcessor,`, this seems to work as designed. So this seems to be more a case of "unexpected UI behaviour" than a straight up bug. I'll have to dig around a bit to see if it makes sense to make the selected type the target of the action in this case.

**Comment by tsmaeder** [comment] 2022-07-25 09:39
If you select a member of the class `B` in the above example, the refactoring correctly extracts a superclass of `B`. As far as I can tell from the code in `ExtractSupertypeProcessor,`, this seems to work as designed. So this seems to be more a case of "unexpected UI behaviour" than a straight up bug. I'll have to dig around a bit to see if it makes sense to make the selected type the target of the action in this case.

**Comment by tsmaeder** [comment] 2022-07-25 09:54
If you select the class `B`, the wizard opens with `B` selected as the member to be extracted to the new super class. As far as I'm concerned, this works as designed.

**Comment by tsmaeder** [comment] 2022-07-27 08:28
Closing this one as "works as designed".

**Closed by tsmaeder** 2022-07-27 08:28 UTC
