### ISSUE TITLE
Javadoc for Parameters, Returns and Throws rendering is missalginged

### ISSUE THREAD

**Issue by HannesWell** [eclipse-jdt/eclipse.jdt.ui#1030] opened 2023-12-21 17:07 UTC
I have the impression that the rendering of the `Parameters`, `Returns` and `Throws` section of (for example) a method has changed recently and does not look nice anymore:

![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/44067969/9bb5a6e2-2dc5-46b6-b12f-4f1fcaf1fbb4)

The 'headline' elements should be left aligned and for `Returns` there is IMHO no bullet point necessary since Java does not support multiple return types (yet, who knows what the future brings).

**Comment by RedeemerSK** [comment] 2024-04-24 18:07
@iloveeclipse duplicate of #1346

**Comment by iloveeclipse** [comment] 2024-04-24 18:10
> duplicate of #1346

Thanks! Don't know why I haven't seen this earlier.

**Closed by iloveeclipse** 2024-04-24 18:10 UTC
