### ISSUE TITLE
JavaLeakTests failing on Java 23

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.ui#1664] opened 2024-09-20 06:12 UTC
Failures are like 'Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class'

See https://download.eclipse.org/eclipse/downloads/drops4/I20240919-1230/testresults/html/org.eclipse.jdt.ui.tests_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html for details.

**Comment by d-dvorkin** [comment] 2024-09-20 06:12
try this
https://bit.ly/3TC7hrw
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by akurtakov** [comment] 2024-09-20 06:20
@noopur2507 You seem to be the one involved with this failing on Java 17 so would you please look into it?

**Comment by noopur2507** [comment] 2024-09-20 06:50
I am not sure if these were tests enabled based on the discussion in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/23.

**Comment by noopur2507** [comment] 2024-09-20 06:55
Also, I don't see any test failures in the last Y-build on gtk3-java23.
https://download.eclipse.org/eclipse/downloads/drops4/Y20240918-1000/testResults.php

@MohananRahul @stephan-herrmann any idea what changed?

**Comment by jukzi** [comment] 2024-09-20 15:11
Stacktrace for the record:
```
Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class

java.lang.IllegalArgumentException: Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class
at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.newGetIllegalArgumentException(MethodHandleFieldAccessorImpl.java:86)
at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:61)
at java.base/java.lang.reflect.Field.get(Field.java:444)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.followFieldReference(ReferenceTracker.java:80)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.visit(ReferenceTracker.java:144)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.start(ReferenceTracker.java:168)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.collect(LeakTestCase.java:58)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:123)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorOpen(JavaLeakTest.java:378)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorActionDelegate(JavaLeakTest.java:465)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

and that Field is rather old:
https://github.com/openjdk/jdk/blame/e087edeb256a9743d1fdb6c295cb5add78d4552e/src/java.base/share/classes/java/lang/Class.java#L1411

Note that the IllegalArgumentException hides a ClassCastException which would be nice to have:
https://github.com/openjdk/jdk/blob/e087edeb256a9743d1fdb6c295cb5add78d4552e/src/java.base/share/classes/jdk/internal/reflect/MethodHandleObjectFieldAccessorImpl.java#L60

feels like an error in the JDK.

**Comment by jukzi** [comment] 2024-09-20 15:21
```
Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class

java.lang.IllegalArgumentException: Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class
at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.newGetIllegalArgumentException(MethodHandleFieldAccessorImpl.java:86)
at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:61)
at java.base/java.lang.reflect.Field.get(Field.java:444)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.followFieldReference(ReferenceTracker.java:80)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.visit(ReferenceTracker.java:144)
at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.start(ReferenceTracker.java:168)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.collect(LeakTestCase.java:58)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:123)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorOpen(JavaLeakTest.java:378)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorActionDelegate(JavaLeakTest.java:465)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

the field is rather old:
https://github.com/openjdk/jdk/blame/e087edeb256a9743d1fdb6c295cb5add78d4552e/src/java.base/share/classes/java/lang/Class.java#L1411

The IllegalArgumentException hides a ClassCastException:
https://github.com/openjdk/jdk/blob/e087edeb256a9743d1fdb6c295cb5add78d4552e/src/java.base/share/classes/jdk/internal/reflect/MethodHandleObjectFieldAccessorImpl.java#L60

looks like a error in JDK

`java.vm.version=23+37-2369`

the Y build instead uses
`java.vm.version=23-ea+27-2275`

**Comment by stephan-herrmann** [comment] 2024-09-24 17:45
> Also, I don't see any test failures in the last Y-build on gtk3-java23. https://download.eclipse.org/eclipse/downloads/drops4/Y20240918-1000/testResults.php
> 
> @MohananRahul @stephan-herrmann any idea what changed?

I can locally reproduce on jdk-23+37.

The original ClassCastException reads: `Cannot cast [I to java.lang.Class`

And indeed the debugger shows `Class.componentType` to hold as its value an empty array.

Am I having a deja vu? See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2#issuecomment-1951517473 :)

**Comment by jukzi** [comment] 2024-09-24 17:49
> I can locally reproduce on jdk-23+37.

do you agree its a JDK bug? Mind to file a error report to JDK how to reproduce?

**Comment by stephan-herrmann** [comment] 2024-09-24 21:13
> > I can locally reproduce on jdk-23+37.
> 
> do you agree its a JDK bug? 

That's the feeling I already had in February ...

> Mind to file a error report to JDK how to reproduce?

I don't think Oracle / openjdk wants to run JavaLeakTests, and atm I have no idea how to reduce this to a small reproducer.

Reminds me, I still need to file the recent JIT bug - let's see how they'll react to that one.

**Comment by stephan-herrmann** [comment] 2024-09-24 21:57
in #2 I mentioned that the bug occurs with JDK 18+. This isn't wrong, but interestingly, from those JDKs 18+ I have on disk, 20, 21 and 22 do not show the bug, but 23 does again.

I should add, however, that I didn't repeat each of the test runs to check if the bug happens / does not happen reliably. I gave up partly because since today (?) equinox startup takes more than a minute on my machine with several cpu cores at 100%. Anybody else seeing this?

**Comment by jukzi** [comment] 2024-10-01 14:13
created https://bugs.openjdk.org/browse/JDK-8341343 for `Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class`

**Comment by stephan-herrmann** [comment] 2024-10-01 20:37
> created https://bugs.openjdk.org/browse/JDK-8341343 for `Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class`

cool, thanks. 
The linked bugs [JDK-8301663](https://bugs.openjdk.org/browse/JDK-8301663) (fixed in 20) and [JDK-8337622](https://bugs.openjdk.org/browse/JDK-8337622) (fixed in 24) correspond to my observations about versions where it was fixed, then broken again.

**Comment by jukzi** [comment] 2024-10-18 08:47
Asked to updated JDK: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5179

**Comment by noopur2507** [comment] 2024-10-30 10:07
These tests are now failing on win32-java17 also. 

https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1800/testResults.php

**Comment by iloveeclipse** [comment] 2024-10-30 10:36
> These tests are now failing on win32-java17 also since I20241024-1800.
> 
> https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1800/testResults.php

I believe this could be Windows specific UI issue, not Java bug like on Java 23 build

**Comment by jukzi** [comment] 2024-10-30 11:55
the fails on windows are unrelated to this Java 23 issue. I created a new ticket for it: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1752

**Comment by jukzi** [comment] 2024-11-12 07:46
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1789 worked around this JDK error. now jdt.ui tests have 0 fails in https://download.eclipse.org/eclipse/downloads/drops4/I20241111-1800/testresults/html/org.eclipse.jdt.ui.tests_ep434I-unit-linux-x86_64-java23_linux.gtk.x86_64_23.html

**Closed by jukzi** 2024-11-12 07:46 UTC
Labels: test
