### ISSUE TITLE
Run As/Debug As context menu in java source editor and package explorer does not show entries

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-jdt/eclipse.jdt.ui#1068] opened 2024-01-15 11:11 UTC
With Eclipse (Linux)

```
Version: 2024-03 M1 (4.31.0 M1)
Build id: 20240111-1612
```

and  Eclipse Java Development Tools 3.19.400.v20240104-1800

the Run As/Debug As context menu in java source editor and package explorer does not show entries; at least, not in a usable way, see the screenshot:

![Screenshot_20240115_120955](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/1202254/5dcbe3f2-8738-4cc4-8194-0f209791465b)

On the contrary, the ones in the toolbar and in the "Run" menu work as expected.

**Comment by jukzi** [comment] 2024-01-15 11:20
please have a look in the "Error Log" view if you find a related exception

**Comment by LorenzoBettini** [comment] 2024-01-15 11:23
@jukzi the error log doesn't show anything in that respect.

The terminal from where I started Eclipse shows (after using "Run As"):

```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

**Comment by iloveeclipse** [comment] 2024-01-15 14:22
I don't think this is JDT problem, most likely GTK / SWT issue on HiDPI monitors / Wayland.
Please try to either use X11 or switch to "low" DPi and see if the problem disappears.
If not, please provide SWT/GTK config lines you can find in Help->About->Installation Details->Configuration.

**Comment by LorenzoBettini** [comment] 2024-01-15 14:33
I'm on X11, not Wayland.
I'll try also lower DPI.
Concerning the config lines, is it enough to copy everything that "Configuration" provides if I type "gtk" in the search field?

**Comment by iloveeclipse** [comment] 2024-01-15 16:46
No, please provide these entries that shown for SWT **and** for GTK from "*** System properties" and "*** System environment variables" sections

**Comment by LorenzoBettini** [comment] 2024-01-16 08:19
@iloveeclipse I tried both with X11 and Wayland and I also switched to 100% HDPI (so, no scaling); the result is always the same, and so are the logged information in the terminal.

These are the entries you asked for:

```
*** System properties:
gtk
/home/bettini/eclipse/bundlepool/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.800.v20231003-1442/eclipse_11802.so
org.eclipse.swt.internal.gtk.theme=Adwaita:light:dark
org.eclipse.swt.internal.gtk.version=3.24.39
osgi.ws=gtk

*** System environment variables:
GTK_THEME=Adwaita:light

*** System properties:
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
org.eclipse.swt.graphics.Resource.reportNonDisposed=true
org.eclipse.swt.internal.deviceZoom=100
org.eclipse.swt.internal.gdk.backend=x11
org.eclipse.swt.internal.gtk.theme=Adwaita:light:dark
org.eclipse.swt.internal.gtk.version=3.24.39

*** System environment variables:
```

**Comment by jukzi** [comment] 2024-01-17 11:34
@mickaelistria @fedejeanne  can this issue relate to the changes in run menu? for example  https://github.com/eclipse-platform/eclipse.platform/pull/1005

**Comment by mickaelistria** [comment] 2024-01-17 12:51
@jukzi yes probably. @fedejeanne I suspect the issue is that the menu doesn't refresh its layout well and remains too small to show the entries.

**Comment by LorenzoBettini** [comment] 2024-01-21 14:20
But, just for curiosity, am I the only one seeing this problem? By the way, I can see that in all my Linux installations. Not on mac m1, though.

**Comment by mickaelistria** [comment] 2024-01-21 19:43
I noticed it yesterday on Linux as well. I think it's related to async computation of submenus/items which menu ignores when computing its size.
I see the same issue with async dynamic inputs in menus in LSP4E > Code Actions: the menu looks empty while is has some contents; here too, computation is async.

**Comment by jukzi** [comment] 2024-01-22 08:30
@fedejeanne pleae fix or revert

**Comment by LorenzoBettini** [comment] 2024-01-22 08:31
Unpopular opinion: life is much better with blocking operations and without concurrency/asynchronicity... ;)

**Comment by LorenzoBettini** [comment] 2024-02-13 08:13
Sorry for the ping, but this bug is critical concerning usability...

**Comment by mickaelistria** [comment] 2024-02-13 09:16
@LorenzoBettini Can you please submit a fix or revert PR?

**Comment by LorenzoBettini** [comment] 2024-02-13 09:22
@mickaelistria I think the original author should do the fix or, better, the revert of the PR. I don't know the internals of JDT; the original author should, and it should be a matter of minutes. For me, it would take ages...
I'm happy to help, but also time optimization is important ;)

**Comment by jukzi** [comment] 2024-02-13 09:27
Please name the PR that causes the issue so that we can revert.

**Comment by LorenzoBettini** [comment] 2024-02-13 09:39
> @mickaelistria @fedejeanne can this issue relate to the changes in run menu? for example [eclipse-platform/eclipse.platform#1005](https://github.com/eclipse-platform/eclipse.platform/pull/1005)

@jukzi you mentioned the change

**Comment by jukzi** [comment] 2024-02-13 09:40
> @jukzi you mentioned the change

that was a guess... did you verify a revert of that helps?

**Comment by iloveeclipse** [comment] 2024-02-13 16:31
I've just reported another issue related to this code, see https://github.com/eclipse-platform/eclipse.platform/issues/1202.

I would propose to revert the **two** related commits as they both are part of same feature.
- https://github.com/eclipse-platform/eclipse.platform/commit/494483ea135ec22a0327ec4c9500c693555d710f
- https://github.com/eclipse-platform/eclipse.platform.ui/commit/771d0b405910c4971123ffb46b09b9693d10af4e

**Comment by jukzi** [comment] 2024-02-13 16:36
please do, when you know that they cause this issues. @fedejeanne had enough time to repsond.

**Comment by iloveeclipse** [comment] 2024-02-13 18:45
@LorenzoBettini : please check next IBuild, I've reverted related commits.
At least https://github.com/eclipse-platform/eclipse.platform/issues/1202 is fixed by that.

**Comment by LorenzoBettini** [comment] 2024-02-14 07:38
@iloveeclipse I'm trying to use https://download.eclipse.org/eclipse/updates/4.31-I-builds/ for updating "platform", I guess the hopefully fixed version is [org.eclipse.platform_4.31.0.v20240213-2236.jar](https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.31-I-builds/I20240213-1800/features/org.eclipse.platform_4.31.0.v20240213-2236.jar)

However, it refuses to update because of the conflict with the EPP package

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Platform 4.31.0.I20240213-1800 (org.eclipse.platform.ide 4.31.0.I20240213-1800)
  Software currently installed: Eclipse Platform 4.31.0.v20240127-1800 (org.eclipse.platform.feature.group 4.31.0.v20240127-1800)
  Only one of the following can be installed at once: 
    Compare Support 3.9.300.v20231123-2204 (org.eclipse.compare 3.9.300.v20231123-2204)
    Compare Support 3.10.0.v20240104-0951 (org.eclipse.compare 3.10.0.v20240104-0951)
    Compare Support 3.10.0.v20240208-0728 (org.eclipse.compare 3.10.0.v20240208-0728)
    Compare Support 3.9.200.v20230726-0617 (org.eclipse.compare 3.9.200.v20230726-0617)
    Compare Support 3.10.0.v20240125-0912 (org.eclipse.compare 3.10.0.v20240125-0912)
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240127-1800 (org.eclipse.platform.feature.group 4.31.0.v20240127-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.compare [3.10.0.v20240125-0912,3.10.0.v20240125-0912]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240213-2236 (org.eclipse.platform.feature.group 4.31.0.v20240213-2236)
    To: org.eclipse.equinox.p2.iu; org.eclipse.compare [3.10.0.v20240208-0728,3.10.0.v20240208-0728]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.I20240213-1800 (org.eclipse.platform.ide 4.31.0.I20240213-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.31.0.v20240213-2236,4.31.0.v20240213-2236]
```

However, I could update my TP and start a new Eclipse workbench. I see the problem went away in the started workbench!
So it looks like it is fixed now.

**Comment by iloveeclipse** [comment] 2024-02-14 08:00
> So it looks like it is fixed now.

Perfect, thanks for confirmation. Closing as duplicate of https://github.com/eclipse-platform/eclipse.platform/issues/1202.

**Closed by iloveeclipse** 2024-02-14 08:00 UTC
Labels: bug, regression

**Comment by fedejeanne** [comment] 2024-04-02 05:39
Hello everyone,
I came back from a leave of several months just recently, hence the radio silence. Sorry to hear that my change brought some problems, thanks @LorenzoBettini for reporting it!

I've been looking into it and I couldn't find anything useful on the bug on `pixman_region32_init_rect` nor could I come up with a solution for Linux, so I guess there's no other choice besides removing it.

> Unpopular opinion: life is much better with blocking operations and without concurrency/asynchronicity... ;)

I agree (sigh)
