### ISSUE TITLE
memory leak: ITestElement

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1076] opened 2024-01-16 10:32 UTC
Today my eclipse went into OOME

eclipse.buildId=4.31.0.I20240115-1800
java.version=21.0.1

HeapDump shows 1,5GB Data polluted with ITestElement. i have never seen that before - was there a recent change related?
i had executed for example org.eclipse.jdt.core.tests.compiler.regression.TestAll before.
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/e7af5575-c80f-4de1-9adc-81712fcaee2c)

**Comment by jukzi** [comment] 2024-01-16 11:21
memory consumption during org.eclipse.jdt.core.tests.compiler.regression.TestAll (137746 tests):
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/eb5d9a60-8133-4239-9232-e2bd27491b9e)

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/c67d9787-8c66-4f63-b965-f4f19d540d8e)

**Comment by jukzi** [comment] 2024-01-16 11:22
GC root of an example ITestElement []:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/7d60f74c-62a1-413f-9de4-d3d6b204040b)

**Comment by jukzi** [comment] 2024-01-16 13:24
@iloveeclipse  @raghucssit this is probably a regression from [ee92e3de6f124b554ceca47135babea27831d04b](https://github.com/eclipse-platform/eclipse.platform.ui/pull/810)

as the org.eclipse.jdt.internal.junit.model.TestCaseElement is referenced by  org.eclipse.jface.viewers.internal.ExpandableNode.orginalArray multiple times:

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/1d4b684f-1be0-4f76-83d2-21167e70b649)

**Comment by raghucssit** [comment] 2024-01-16 14:24
@iloveeclipse **we maintain this list of expandable nodes to select the expandable node in case of element to select is present inside it** 
Usually when an expandable node is created only when children are expanded. JUnit view tries to expand all the nodes to select the failure. Getting this scenario manually is very rare. Either user should use **Expand All** or manually expand all the nodes(Which is almost rare case).

**Comment by iloveeclipse** [comment] 2024-01-16 14:55
> HeapDump shows 1,5GB Data polluted with ITestElement. i have never seen that before

With exact this test case? Note: the number of tests (and so required memory) depends on the JVM used to run tests, because JDT decides which test to run based on JVM version. So running this test on Java 17 results in less tests executed if running it on Java 21.

> as the org.eclipse.jdt.internal.junit.model.TestCaseElement is referenced by org.eclipse.jface.viewers.internal.ExpandableNode.orginalArray multiple times

Note, the data that is produced by test does not depend on the "expandable" feature enabled or not, the JFace always keeps the content elements linked to UI in memory. So you can switch the preference on/off and see *exact* same number of org.eclipse.jdt.internal.junit.model.TestCaseElement references kept in memory (I did it and see same number of objects on heap).

Just think / try: **every** node in the tree, if selected, shows you/gives you a link/reference to TestCaseElement. That's unavoidable.

> this is probably a regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/810

I don't think this is a regression at all, see above. The data produced by test and linked to elements in the tree **is always** in memory.

**Comment by iloveeclipse** [comment] 2024-01-16 16:03
ITestElement[] memory is only to store the "hidden" TestCaseElement's but their number is same.
So what you see is the effect of "memory vs speed" trade off, not a memory leak.
In order to avoid UI freezes (speed) we need extra data structures (memory), nothing is for free.

But beside this, which preference value have you set for the viewer limit & how many ExpandableNode instances are related to the JUnit view? In my case (default 1000 limit & 371907 TestCaseElement's) I see **one** instance of ExpandableNode and **one** instance of  ITestElement[], this is what the jcmd GC.class_histogram command says.

**Comment by jukzi** [comment] 2024-01-16 16:12
i had used the default values 
4614 ExpandableNode 
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/d64f7216-0eb0-4b7d-a56e-42b3a9f47d9b)
do you want the heap dump?

**Comment by jukzi** [comment] 2024-01-16 16:18
> So what you see is the effect of "memory vs speed" trade off, not a memory leak.

maybe not a leak but a huge waste of memory, especially since the node limit was never reached. 
I don't even understand why there are thousends of ITestElement[] with almost 137746 items EACH, when there are only 137746 in total.
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/1c4a4b5f-b52a-4978-aba9-4d1e91c70bd9)

**Comment by iloveeclipse** [comment] 2024-01-16 16:55
Jörg, there must be 1:1 ExpandableNode / ITestElement[] relationship, so the question is more why are there so many  ExpandableNode created in your case. 

Just to make sure we are on same level of data: could you please run 
`jcmd <pid_of_Eclipse> GC.class_histogram` and check that the number of ExpandableNode / ITestElement[] instances matches what you see in the heap dump? So far I always trusted jcmd data, and I can only explain difference between your instances number and my with different OS / SWT implementation (Windows vs Linux).

**Comment by jukzi** [comment] 2024-01-17 08:00
the jcmd output matches the VisualVm Data from a heapdump - both size and count:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/14d2194b-f773-461b-aa07-7ab496e867cd)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/0a4f2ab2-7b93-43ac-b414-7e7aafb46d4c)

**Comment by jukzi** [comment] 2024-01-17 08:07
hey that jcmd is handy fast. That way i can monitor the object count. turns out the ExpandableNode count increases every Time i click on the "Unrooted Tests" Node. While the test is running that Node immediately collapses again (don't know why, feels like an error) an seems to leak 1 ExpandableNode
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/6d7af481-2208-4ca4-932c-288476bebbbc)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/d5087218-4019-4447-94dc-f88599a56d3a)

**Comment by jukzi** [comment] 2024-01-17 08:10
When "Scroll Lock" is off the ExpandableNode count increases fast without manually clicking
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/74a6fcd0-8a0e-4904-984a-fdf81deedf39)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/2aaba4f8-487e-49bb-b534-81ea4781f371)

**Comment by iloveeclipse** [comment] 2024-01-17 10:34
OMG. That looks like a memory leak in Windows / SWT port.
@raghucssit : we should check what happened with Windows. I assume the node element is not disposed properly.

**Comment by raghucssit** [comment] 2024-01-17 12:34
I will check.

**Comment by iloveeclipse** [comment] 2024-01-19 09:32
The fix is merged in platform UI repo via https://github.com/eclipse-platform/eclipse.platform.ui/pull/1521

**Closed by iloveeclipse** 2024-01-19 09:32 UTC
Labels: bug, regression
