### ISSUE TITLE
[code mining] Annotations are replaced with empty space (regression in 2023-09)

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.ui#845] opened 2023-10-04 13:52 UTC
I encountered a problem with code mining which might be a regression for Eclipse 2023-09. The only code mining annotation I'm using is "Show method parameter names".

The effect: I open a class and the parameter names are shown correctly. Then I scroll up and down a bit while working and suddenly some annotations are no longer shown. Instead empty space is shown instead:

Good:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/10562923/3351a1ae-a3d7-4ecf-9fa8-dd633931c046)

Bad:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/10562923/ac55f612-f54a-4011-939c-f62dd11715b8)

Note that this happens on all classes after a while. After this became annoying I downloaded 2023-06 again to verify and it seems that this is only a problem with 2023-09.

I'm using a M2 MacBook with Sonoma. I downloaded the AArch64 version for 06 and 09.

Any ideas or hints?

**Comment by iloveeclipse** [comment] 2023-10-04 13:57
@jubax : can you see it on Windows or Linux, and could you please provide a simple Java file showing the problem?

@mickaelistria : probably this should be moved to platform UI? Looks like a generic code mining drawing issue (on Mac)?

**Comment by iloveeclipse** [comment] 2023-10-04 16:47
Closing as duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1170

**Closed as completed by iloveeclipse** 2023-10-04 16:47 UTC
Labels: needinfo

**Comment by jubax** [comment] 2023-10-04 17:19
> > What is the best way to get this bug fixed locally for 2023-09 (J2EE)? Just replace the .class files from the JAR file or replace a plug-in/library with a new version? What would you recommend?
> 
> You basically cannot do it easily because the release block a certain version of the Platform. The best approach is more to start from an I-Build of Platform, install what you need into it. Then you could just run updates from time to time to get fixes between releases.

Thank you, I will try that.
