### ISSUE TITLE
Inline module info question

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#59] opened 2022-05-19 05:44 UTC
Would it be possible to inline the options of module info in the Java project wizard page?

![image](https://user-images.githubusercontent.com/139910/169218664-50819145-1653-40cc-9549-f4480346671c.png)

All the other options are set on the first page, only the module info is done via an additional popup which feels weird and IMHO is bad UX.

**Comment by vogella** [comment] 2022-05-19 05:44
cc @tsmaeder and @jjohnstn

**Comment by ktatavarthi** [comment] 2022-05-19 05:53
This is a duplicate of thye bug [Bug 560840 - [9] There should be someway to avoid the module name dialog during Java Project creation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560840), which I plan to work on in 4.25 M1

**Comment by vogella** [comment] 2022-05-19 06:07
Very nice, as bugzilla is more or less dead, I will mark the bugzilla one as moved to Github.

**Closed** 2022-06-10 06:07 UTC
Labels: enhancement

**Comment by SarikaSinha** [comment] 2022-07-07 07:43
@ktatavarthi 
Only problem I am facing with this is that the added segment on Java Project wizard Page is not displayed by default (atleast for me). Only if I scroll down I can see that.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/14090181/177719124-f645b84c-9027-49db-9967-425a6d2e1530.png">

What are the options to move it up? How can we reorganize the page?
Can we move Project Layout and Working Set stuff down? Is that used frequently?
