### ISSUE TITLE
javadoc does not work for public fields

### ISSUE THREAD

**Issue by bildechinger** [eclipse-jdt/eclipse.jdt.ui#1252] opened 2024-03-11 20:47 UTC
Using Eclipse IDE for Java Developers version 4.30.0.20231201-1200.

Javadoc-View does not work on public fields of external jars on the classpath. Javadoc is configured to read from a doc-jar-file.

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/13014910/c8818d12-47cf-48f5-a788-8d311400a51a)
[JavadocIssue.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/14564411/JavadocIssue.zip)

**Comment by iloveeclipse** [comment] 2024-03-11 20:51
Is this a regression? If yes, in which release was it working?

**Comment by bildechinger** [comment] 2024-03-11 21:09
Same behavior already in version "2020-09 (4.17)". I can't go back further.

**Comment by bildechinger** [comment] 2024-03-11 21:26
I think the javadoc-format changed and this is causing this issue. 
I went back to an older build of the library "jackson-core-2.11.0-javadoc.jar" and it works with this javadoc-package!

**Comment by iloveeclipse** [comment] 2024-03-11 21:28
Perfect. Now if you could point to the difference in format?

**Comment by bildechinger** [comment] 2024-03-11 22:04
Change is significant. I assume Eclipse parses the html-files but I don't know what html-tag is relevant.
Search for "" in both files and compare. 

[Base64Variant.html_2.11.txt](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/14564945/Base64Variant.html_2.11.txt)
[Base64Variant.html_2.16.txt](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/14564946/Base64Variant.html_2.16.txt)

**Comment by iloveeclipse** [comment] 2024-03-19 14:16
See more details on https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1262

**Comment by iloveeclipse** [comment] 2024-04-18 09:30
Closing this one as duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1262, which is more generic (not only fields are missing unfortunately).

**Closed** 2024-04-23 16:42 UTC
Labels: bug
