### ISSUE TITLE
Eclipse 4.31 line distance in Outline window etc.

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-jdt/eclipse.jdt.ui#1265] opened 2024-03-16 10:10 UTC
Hello all,
it occurred to me that 4.31 differs from 4.30 by a larger vertical line space in the windows:
Outline, Package Explorer, Search and Problems, but NOT in Console.
Is this fixed or is it settable by parameter somewhere.

The phenomenon is not very unpleasant, but space consuming, particularly on my smaller laptop screen.
;JOOP!

**Comment by iloveeclipse** [comment] 2024-03-16 10:12
Duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1674

**Closed by iloveeclipse** 2024-03-16 10:12 UTC
