### ISSUE TITLE
Enable LeakTestSite in org.eclipse.jdt.ui.tests pom.xml again

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#5] opened 2022-04-10 12:42 UTC
This change comments out LeakTestSite in org.eclipse.jdt.ui.tests pom.xml , as these test are failing in the jenkins github job.

_Originally posted by @ktatavarthi in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1#issuecomment-1093684675_

**Comment by ktatavarthi** [comment] 2022-04-11 03:21
This a duplicate of #2

**Closed by ktatavarthi** 2022-04-11 03:21 UTC
