### ISSUE TITLE
"Java editor - sometimes refuses to format code"

### ISSUE THREAD

**Issue by daniel-matheis-vivavis** [eclipse-jdt/eclipse.jdt.ui#720] opened 2023-08-16 09:58 UTC
Originally this bug report was used to report the problem: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=582110 
[Bug 582110](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582110) - Java editor - sometimes refuses to format code

I assume that this location here is hopefully the right one to report about it.
In the linked issue I have attached a demo project to reproduce the problem (https://bugs.eclipse.org/bugs/attachment.cgi?id=289150).

**Comment by Madjosz** [comment] 2023-09-27 11:28
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/609

**Closed** 2023-09-27 11:53 UTC
