### ISSUE TITLE
NPE in NodeFinder:186

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#212] opened 2022-08-10 14:03 UTC
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.dom.ASTNode.accept(org.eclipse.jdt.core.dom.ASTVisitor)" because "root" is null
	at org.eclipse.jdt.core.dom.NodeFinder.<init>(NodeFinder.java:186)
	at org.eclipse.jdt.core.dom.NodeFinder.perform(NodeFinder.java:103)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaSourceHover.getTextBlockHoverInfo(JavaSourceHover.java:446)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaSourceHover.getHoverInfo(JavaSourceHover.java:149)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaSourceHover.getHoverInfo2(JavaSourceHover.java:127)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

root == null in constructor

getTextBlockHoverInfo() needs to check if ast==null

**Comment by jukzi** [comment] 2022-08-10 14:04
relates to "JavaSourceHover support for TextBlock. Fixes #164 (#165)

**Comment by jukzi** [comment] 2022-08-10 14:04
@ktatavarthi  can you take a look?

**Comment by ktatavarthi** [comment] 2022-08-10 14:34
This is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/200

**Closed by ktatavarthi** 2022-08-10 14:34 UTC
Labels: duplicate
