### ISSUE TITLE
JavaLeakTest fail on windows since I20241021-0550

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1752] opened 2024-10-30 11:55 UTC
https://download.eclipse.org/eclipse/downloads/drops4/I20241021-0550/testresults/html/org.eclipse.jdt.ui.tests_ep434I-unit-win32-java17_win32.win32.x86_64_17.html

locally reproducable (jdk-21.02.+13)

for example:

```
java.lang.AssertionError: Expected instance count: 0, actual: 1
Element 0
org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor
  org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer#this$0 -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor@47d45509
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.EditorBreadcrumb#fTextViewer -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer@75f0f0ce
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.EditorBreadcrumb$$Lambda/0x000001ea18e9d510#arg$1 -> org.eclipse.jdt.internal.ui.javaeditor.JavaEditorBreadcrumb@70ad3365
  java.lang.Object[0] -> org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.EditorBreadcrumb$$Lambda/0x000001ea18e9d510@570c7
  org.eclipse.core.runtime.ListenerList#listeners -> [Ljava.lang.Object;@5d6b1772
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbViewer#fMenuListeners -> [org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.EditorBreadcrumb$$Lambda/0x000001ea18e9d510@570c
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbItem#fParent -> org.eclipse.jdt.internal.ui.javaeditor.JavaEditorBreadcrumb$ProblemBreadcrumbViewer@827fd19
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbItemDropDown#fParent -> BreadcrumbItem {*Disposed*}
  org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbItemDropDown$AccessibleArrowImage#this$0 -> org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbItemDropDown@13d5c9ab
  org.eclipse.jface.resource.ImageDescriptor$$Lambda/0x000001ea18b00000#arg$1 -> org.eclipse.jdt.internal.ui.javaeditor.breadcrumb.BreadcrumbItemDropDown$AccessibleArrowImage@3c795
  org.eclipse.swt.graphics.Image#imageDataProvider -> org.eclipse.jface.resource.ImageDescriptor$$Lambda/0x000001ea18b00000@3189c4dc
  java.util.concurrent.ConcurrentHashMap$Node#key -> Image {*DISPOSED*}
  java.util.concurrent.ConcurrentHashMap$Node[341] -> Image {*DISPOSED*}=true
  java.util.concurrent.ConcurrentHashMap#table -> [Ljava.util.concurrent.ConcurrentHashMap$Node;@7764ef1d
  java.util.concurrent.ConcurrentHashMap$CollectionView#map -> {Image {9903175}=true, Image {12590217}=true, Image {*DISPOSED*}=true, Image {*DISPOSED*}=true, Pat
  org.eclipse.swt.graphics.Device#resourcesWithZoomSupport -> [Image {9903175}, Image {12590217}, Image {*DISPOSED*}, Image {*DISPOSED*}, Pattern {*DISPOSED*}, I
  org.eclipse.ui.internal.Workbench#display -> org.eclipse.swt.widgets.Display@7d070ef5
  org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl#service -> org.eclipse.ui.internal.Workbench@e7529ac
  java.lang.Object[304] -> {org.eclipse.ui.IWorkbench}={service.id=309, service.bundleid=538, service.scope=singleton, id=4125
  java.util.ArrayList#elementData -> [Ljava.lang.Object;@6889e714
  org.eclipse.osgi.internal.serviceregistry.ServiceRegistry#allPublishedServices -> [{org.eclipse.osgi.framework.log.FrameworkLog}={service.id=4, service.bundleid=0, service.scope=bun
  org.eclipse.osgi.internal.framework.EquinoxContainer#serviceRegistry -> org.eclipse.osgi.internal.serviceregistry.ServiceRegistry@74e1d60b
  org.eclipse.osgi.internal.loader.BundleLoader#container -> Equinox Container: cf6b04b2-d630-43bf-871c-f43e93244ab0
  org.eclipse.osgi.internal.loader.EquinoxClassLoader#delegate -> org.eclipse.jdt.ui.tests_3.15.700.qualifier
  org.eclipse.osgi.internal.loader.EquinoxClassLoader -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@6823f652[org.eclipse.jdt.ui.tests:3.15.700.qual

. Actual: 0
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failEquals(Assert.java:187)
	at org.junit.Assert.assertNotEquals(Assert.java:201)
	at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:129)
	at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorClose(JavaLeakTest.java:339)
	at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorBreadcrumbCloseAll(JavaLeakTest.java:198)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)


```

**Comment by jukzi** [comment] 2024-10-30 11:56
![image](https://github.com/user-attachments/assets/0d156d01-348e-4e41-9138-8417a02f38db)

**Comment by jukzi** [comment] 2024-10-30 12:03
Note that it did not fail in https://download.eclipse.org/eclipse/downloads/drops4/I20241014-0530/testResults.php or before. Between 10-14 and 10-21 the I build did not run on windows at all.

**Comment by jukzi** [comment] 2024-10-30 12:07
This may indicate a serious resource leak. i do not fully understand the error message but the 
`Device#resourcesWithZoomSupport -> [Image` may indidicate a resource leak due to SWT changes. 
@HeikoKlare any idea?

**Comment by HeikoKlare** [comment] 2024-10-30 13:52
This seems to be introduced by https://github.com/eclipse-platform/eclipse.platform.swt/pull/1477
Reverting the commit of the PR makes the tests succeed again. Reproduction is easiest with just executing `JavaLeakTest#testJavaEditorBreadcrumbCloseAll()`.
Might either be because the test makes a false assumption that does not hold with the SWT change anymore or because the SWT commit produced a regression. The latter is of course the more likely case. We will have a look (@amartya4256 @akoch-yatta, @fedejeanne) and either come up with a solution or revert that commit for M3 and reapproach the functionality for M1.

**Comment by HeikoKlare** [comment] 2024-10-31 08:06
This should have been fixed via https://github.com/eclipse-platform/eclipse.platform.swt/pull/1565
We can validate this with tomorrow's I-Build.

**Comment by HeikoKlare** [comment] 2024-11-02 10:31
Recent I-Build results show that https://github.com/eclipse-platform/eclipse.platform.swt/pull/1565 has fixed this issue:
https://download.eclipse.org/eclipse/downloads/drops4/I20241101-1800/testResults.php

@jukzi maybe you want to close this issue (I have no permission to do so)

**Closed** 2024-11-02 11:54 UTC
Labels: bug, Windows, regression, test
