### ISSUE TITLE
[code mining] code disappear

### ISSUE THREAD

**Issue by danibs** [eclipse-jdt/eclipse.jdt.ui#522] opened 2023-04-07 14:22 UTC
Activating code mining sometime code disappear:

![immagine](https://user-images.githubusercontent.com/30932554/230624705-fd6d81a3-e41e-496e-bb06-999df29a5e6e.png)

Spring Tool Suite 4 
Version: 4.17.2.RELEASE
Build Id: 202301310704
Revision: 4c43862ec9482cb5c289960e5514998e59d2f1fe

**Comment by agentgt** [comment] 2023-10-10 16:48
I have this problem as well. I thought it was my theme and font color but when you scroll you can see the code mining.

Basically just like in your screen the last 5 or so lines closest to the bottom pane will render the code mining.

**Comment by xmichael91** [comment] 2023-11-08 14:32
Same for me, was fine in Eclipse 4.27.0 (JDT 3.19.0), but after I upgraded to Eclipse 4.29.0 (JDT 3.19.200) the Java Editor looks like this:

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51908948/b88b2f08-69a8-4c82-9dcf-932dd5a572db)

**Comment by agentgt** [comment] 2023-11-08 14:49
@danibs and @xmichael91 are you guys on macOS like me or something else?

**Comment by xmichael91** [comment] 2023-11-08 14:53
@agentgt no, Windows. By the way, found the "proper" bug report and the solution mentioned there is to update to integration build, where the bug is fixed: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/845

**Comment by iloveeclipse** [comment] 2023-11-08 15:21
Should be fixed in 4.30, please check latest build from https://download.eclipse.org/eclipse/downloads/

**Comment by iloveeclipse** [comment] 2023-11-08 20:30
Closing as duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/845

**Closed by iloveeclipse** 2023-11-08 20:30 UTC
